name: Default
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install Dependencies
              run: npm ci
            - name: Build
              run: npm run build
            - name: Archive Production Artifact
              uses: actions/upload-artifact@master
              with:
                  name: build
                  path: build
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install Dependencies
              run: npm ci
            - name: Test
              run: npm run test.coverage
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install Dependencies
              run: npm ci
            - name: Lint
              run: npm run lint
    prettier:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install Dependencies
              run: npm ci
            - name: Prettier
              run: npm run style
    demos:
        name: Run Demos
        needs: [build]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install Dependencies
              run: npm ci
            - name: Download Artifact
              uses: actions/download-artifact@master
              with:
                  name: build
                  path: build
            - name: Run demos
              run: |
                  npm run ts-node -- ./demo/1-basic.ts
                  npm run ts-node -- ./demo/2-declaritive-styles.ts
                  npm run ts-node -- ./demo/3-numbering-and-bullet-points.ts
                  npm run ts-node -- ./demo/4-basic-table.ts
                  npm run ts-node -- ./demo/5-images.ts
                  npm run ts-node -- ./demo/6-page-borders.ts
                  npm run ts-node -- ./demo/7-landscape.ts
                  npm run ts-node -- ./demo/8-header-footer.ts
                  npm run ts-node -- ./demo/9-images-in-header-and-footer.ts
                  npm run ts-node -- ./demo/10-my-cv.ts
                  npm run ts-node -- ./demo/11-declaritive-styles-2.ts
                  npm run ts-node -- ./demo/12-scaling-images.ts
                  npm run ts-node -- ./demo/13-xml-styles.ts
                  npm run ts-node -- ./demo/14-page-numbers.ts
                  npm run ts-node -- ./demo/15-page-break-before.ts
                  npm run ts-node -- ./demo/16-multiple-sections.ts
                  npm run ts-node -- ./demo/17-footnotes.ts
                  npm run ts-node -- ./demo/18-image-from-buffer.ts
                  npm run ts-node -- ./demo/19-export-to-base64.ts
                  npm run ts-node -- ./demo/20-table-cell-borders.ts
                  npm run ts-node -- ./demo/21-bookmarks.ts
                  npm run ts-node -- ./demo/22-right-to-left-text.ts
                  npm run ts-node -- ./demo/23-base64-images.ts
                  npm run ts-node -- ./demo/24-images-to-table-cell.ts
                  npm run ts-node -- ./demo/25-table-xml-styles.ts
                  npm run ts-node -- ./demo/26-paragraph-borders.ts
                  npm run ts-node -- ./demo/27-declaritive-styles-3.ts
                  npm run ts-node -- ./demo/28-table-of-contents.ts
                  npm run ts-node -- ./demo/29-numbered-lists.ts
                  npm run ts-node -- ./demo/30-template-document.ts
                  npm run ts-node -- ./demo/31-tables.ts
                  npm run ts-node -- ./demo/32-merge-and-shade-table-cells.ts
                  npm run ts-node -- ./demo/33-sequential-captions.ts
                  npm run ts-node -- ./demo/34-floating-tables.ts
                  npm run ts-node -- ./demo/35-hyperlinks.ts
                  npm run ts-node -- ./demo/36-image-to-table-cell.ts
                  npm run ts-node -- ./demo/37-images-to-header-and-footer.ts
                  npm run ts-node -- ./demo/38-text-wrapping.ts
                  npm run ts-node -- ./demo/39-page-numbers.ts
                  npm run ts-node -- ./demo/40-line-numbers.ts
                  npm run ts-node -- ./demo/41-merge-table-cells-2.ts
                  npm run ts-node -- ./demo/42-restart-page-numbers.ts
                  npm run ts-node -- ./demo/43-images-to-table-cell-2.ts
                  npm run ts-node -- ./demo/44-multiple-columns.ts
                  npm run ts-node -- ./demo/45-highlighting-text.ts
                  npm run ts-node -- ./demo/46-shading-text.ts
                  npm run ts-node -- ./demo/47-number-of-total-pages-section.ts
                  npm run ts-node -- ./demo/48-vertical-align.ts
                  npm run ts-node -- ./demo/49-table-borders.ts
                  npm run ts-node -- ./demo/50-readme-demo.ts
                  npm run ts-node -- ./demo/51-character-styles.ts
                  npm run ts-node -- ./demo/52-japanese.ts
                  npm run ts-node -- ./demo/53-chinese.ts
                  npm run ts-node -- ./demo/54-custom-properties.ts
                  npm run ts-node -- ./demo/55-math.ts
                  npm run ts-node -- ./demo/56-background-color.ts
                  npm run ts-node -- ./demo/57-add-parent-numbered-lists.ts
                  npm run ts-node -- ./demo/58-section-types.ts
                  npm run ts-node -- ./demo/59-header-footer-margins.ts
                  npm run ts-node -- ./demo/60-track-revisions.ts
                  npm run ts-node -- ./demo/61-text-frame.ts
                  npm run ts-node -- ./demo/62-paragraph-spacing.ts
                  npm run ts-node -- ./demo/63-odd-even-header-footer.ts
    codecov:
        name: Codecov
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: codecov/codecov-action@v1
            with:
                fail_ci_if_error: true
                verbose: true
