name: Demos
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    demos:
        name: Demos
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5
            - uses: "./.github/actions/install-and-build"
            - name: Install xmllint
              run: sudo apt-get update && sudo apt-get install -y libxml2-utils
            - name: Run and validate all demos
              run: bash scripts/run-demos.sh
